### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by matsievskiysv**
Fix most of the compiler warnings (`g++ -Wall -Wextra -pedantic`). Warnings without fix were marked with `FIXME` and `TODO` tags. Some void return warnings were plugged with `throw`.

Code was tested using #23. I was able to run almost all examples without issues (some examples do not have all the files needed for calculation).

PS. Please, create a dev branch, so I wouldn't have to rebase code everyday.

### CODE REVIEW

**Comment by matsievskiysv** [comment]
Rebased to the stable branch

**Comment by halbux** [comment]
Oh, where did you find that std: with a single : ? that's unacceptable and I'll fix it immediately

**Comment by matsievskiysv** [comment]
https://github.com/halbux/sparselizard/blob/master/src/mesh/htracker.cpp#L627

**Comment by halbux** [comment]
Thanks, that std:vector one is now fixed! Strange, visual studio did not complain either although it's clearly illegal.

For the other changes proposed in the commits I generally do not think it will improve anything to change it, in the end it's mostly a matter of coding style and being ok with leaving stuff without any return or without a default case, as long as you can guarantee that they will never be called in a problematic way (and for all I read in the proposed changes I can guarantee that it will not happen).

Furthermore some commit like:

         gradu = mathop::grad(input);                                  // FIXME: return expression is missing

are just going to make wrong outputs. This specific fixme for example makes things wrong and the 1D case is not going through anyways thanks to the above check.

**Pull request closed without merging**
