### PR TITLE
Make MPI dependency optional, add MUMPS

### PR DESCRIPTION
**Pull request by matsievskiysv**
Make MPI dependency optional, add MUMPS dependency.

### CODE REVIEW

**Review by halbux — APPROVED** [review]

**Comment by matsievskiysv** [comment]
Does sparselizard use FFTW library as it's written in [documentation](https://orbi.uliege.be/bitstream/2268/216780/1/DOCUMENTATION.pdf#page=4)?

**Comment by halbux** [comment]
No not anymore, that's the 2 years old documentation (new version is on sparselizard.org)

**Comment by matsievskiysv** [comment]
@halbux I cannot find slepc package in Fedora 31. Do you build it from source?

**Comment by halbux** [comment]
yes, me neither. I ask petsc to build it for me in the petsc configure option in the /install_external_libs/install_petsc.sh script

The usual way of compiling sparselizard is:

1. Run the install_petsc.sh script --> this creates all headers and libs in ~/SLlibs folder
2. make (calls the ~/SLlibs folder for all dependencies)

**Comment by halbux** [comment]
Now in practice slepc is only used for eigenvalues calculation , I could put a flag check to throw an error if not available if slepc really is not in the repos.
You might not need eigenvalues/eigenmodes? (e.g. vibration modes of mechanical parts).

I don't know what kind of simulations you will do btw, what's your goal?

**Comment by matsievskiysv** [comment]
> I could put a flag check to throw an error if not available

No, I don't need it, I just want to simplify a Docker image for rpm-based system. OpenSuse has this lib, so I'll use it instead of Fedora.

> I don't know what kind of simulations you will do btw, what's your goal?

Electromagnetic simulations of ~1MHz-10GHz RF devices. Usually eigenvalue problems and S-matrix calculations.

**Comment by halbux** [comment]
Sounds good. EM wave propagation are currently performed with sparselizard in my research group in 1D, 2D, 2D axisymmetry and 3D. You might be interested in the adaptive mesh/adaptive order (hpFEM) capabilities of sparselizard for e.g. transient EM propagation of bursts,...

**Comment by matsievskiysv** [comment]
For now I'm just reading the manual. Think, I'll ask some questions on your forum soon.

**Pull request merged**
