### PR TITLE
add tests template

### PR DESCRIPTION
**Pull request by matsievskiysv**
Add tests template to the project. Use `ctest` to run tests.

### CODE REVIEW

**Comment by halbux** [comment]
Could you provide more details on the purpose of this pr?
The example folder already provides quite a lot of code validation tests which include a wide range of things working as they should (including densematrix and intdensematrix). I am not sure more tests are needed

**Comment by matsievskiysv** [comment]
This would add ability to [unit test](https://en.wikipedia.org/wiki/Unit_testing) classes, reducing a chance of breaking library. Also, it could be used in automated builds to check PRs.

**Comment by matsievskiysv** [comment]
In another words, if at some point current examples will stop working, you would have to manually find the last working commit (since examples are not running automatically for each commit) and then look for the error in all sources. Automatic build with tests will ensure stable behavior of classes and signal in case of breaking changes.

**Comment by halbux** [comment]
This will never happen because I am the only developper and I am running the validation script on all examples before any commit

**Comment by matsievskiysv** [comment]
Why not automate this?

**Comment by halbux** [comment]
Too many new things appeared over 1 day and I have not so much the feeling that anything became easier to use... it's actually quite easy for me to just run the ./validate.sh script in /examples and come back 15min later to check for an "All ok" message.

**Pull request closed without merging**
